import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { Character, GetCharacterResults } from "../types";
import ImageLoader from "./../imageLoader";

export const getStaticProps: GetStaticProps = async (context) => {
  const response = await fetch("https://rickandmortyapi.com/api/character");
  const characters: GetCharacterResults = await response.json();
  return {
    props: {
      characters,
    },
  };
};

const Home: NextPage<{ characters: GetCharacterResults }> = ({
  characters,
}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {characters.results.map((char: Character) => {
          return (
            <div key={char.id}>
              {char.name}
              <Link href={`/characters/${char.id}`}>
                <a>
                  <Image
                    loader={ImageLoader}
                    unoptimized
                    src={char.image}
                    alt={char.name}
                    width={200}
                    height={200}
                  />
                </a>
              </Link>
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default Home;
